services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DB_CLIENT_URL=postgresql://admin:admin@postgres:5432/mvp
      - PORT=3000
      - APP_ENV=development
      - APP_NAME=technical-test
      - APP_PREFIX=api

  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_DB: mvp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data: {}
